[build]
  command = "yarn run build"

[build.environment]
  NODE_VERSION = "10.15.3"

[[redirects]]
  from = "/talk1"
  to = "/blog/how-being-a-developer-makes-me-a-better-designer"
  status = 301

[[redirects]]
  from = "/talk2"
  to = "/blog/the-rise-of-the-jamstack-dj-set"
  status = 301
