[build]
  command = "yarn run build"

[build.environment]
  NODE_VERSION = "10.15.3"

 [[redirects]]
  from = "/talk1"
  to = "/how-being-a-developer-makes-me-a-better-designer.html"
  status = 301

[[redirects]]
  from = "/talk2"
  to = "/the-rise-of-the-jamstack-dj-set.html"
  status = 302
